<a href="https://colab.research.google.com/github/LohitSubodh/Deep-Learning-with-PyTorch-Zero-to-GANs/blob/main/Imp_PyTorch_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1vIOd24-IGvMyVGxYct2eUZCN32GXrYX9')

> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# PyTorch functions

Pytorch is a library for processing tensors.

- torch.eye
- torch.ranperm
- torch.take
- torch.unbind
- torch.roll

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.eye

returns a 2D tensor with diagonal entries as 1's and rest all are 0.

In [ ]:
# Example 1 - working (change this)
torch.eye(n=2,m=3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

It returns 2*3 matrix with diagonal entries as 1.

In [ ]:
torch.eye(n=3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

If only 1 argument is given it returns 2D tensor of size n*n 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(1.5)

TypeError: ignored

Argument passsed should be an integer not a floating number.


It is used for creating identity matrix.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/2017meb1219/01-tensor-operations


'https://jovian.ai/2017meb1219/01-tensor-operations'

## Function 2 - randperm

Returns a random permutations of integers from 0 to n-1.

In [ ]:
# Example 1 - working
torch.randperm(5)

tensor([3, 0, 4, 2, 1])

It returns tensor with values from 0 to 4 arranged randomly.

In [ ]:
# Example 2 - working
a=torch.rand(3,5)
print(a)
a=a[torch.randperm(a.size()[0])]
print(a)

tensor([[0.6745, 0.5299, 0.6387, 0.1967, 0.3034],
        [0.4206, 0.4410, 0.4002, 0.6840, 0.4158],
        [0.5209, 0.2187, 0.6067, 0.7218, 0.9703]])
tensor([[0.5209, 0.2187, 0.6067, 0.7218, 0.9703],
        [0.4206, 0.4410, 0.4002, 0.6840, 0.4158],
        [0.6745, 0.5299, 0.6387, 0.1967, 0.3034]])


Rows are shuffled using randperm function.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randperm(6,requires_grad=True)

RuntimeError: ignored

Tensors of floating and complex need gradients.

It is mainly used for shuffling purpose.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/2017meb1219/01-tensor-operations


'https://jovian.ai/2017meb1219/01-tensor-operations'

## Function 3 - torch.take

returns a tensor with elements of input tensors at the given indices.

In [ ]:
# Example 1 - working
b = torch.tensor([23, 25, 35, 40, 45])
torch.take(b, torch.tensor([3]))

tensor([40])

Returned element at index 3.

In [ ]:
# Example 2 - working
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
torch.take(a, torch.tensor([5,6]))

tensor([6, 7])

returns element at index 5 and 6.It treats input as 1D tensor.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(a, torch.tensor([7]))

RuntimeError: ignored

Index is out of range. Should be less than the size of tensor.

Used to take entries of tensor along a dimension according to index.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/2017meb1219/01-tensor-operations


'https://jovian.ai/2017meb1219/01-tensor-operations'

## Function 4 - torch.unbind

Removes tensor dimension along  specified dimension

In [ ]:
# Example 1 - working
a = torch.tensor([[1, 2],
                  [4, 5]])
torch.unbind(a)

(tensor([1, 2]), tensor([4, 5]))

Unbinds the tensor along row

In [ ]:
# Example 2 - working
a = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
torch.unbind(a, dim=1)

(tensor([10, 40, 70]), tensor([20, 50, 80]), tensor([30, 60, 90]))

Unbinding is done here along colmuns.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80]])
torch.unbind(a, dim=1)

ValueError: ignored

dimensions must match while unbinding is done along a particular axis.

Used when a tuple of all slices are required for a particluar direction

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/2017meb1219/01-tensor-operations


'https://jovian.ai/2017meb1219/01-tensor-operations'

## Function 5 - torch.roll

Rolls the tensor along given direction.

In [ ]:
# Example 1 - working
x = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)
print(x)
torch.roll(x, 1, 0)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[5, 6],
        [1, 2],
        [3, 4]])

rolling is permofed along rows by 1 place being shifted.

In [ ]:
# Example 2 - working
torch.roll(x, shifts=(2, 1), dims=(0, 1))

tensor([[4, 3],
        [6, 5],
        [2, 1]])

rows are shifted by 2 places and columns are shifted by 1 place.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.roll(x, shifts=(1,2 ), dims=0)

RuntimeError: ignored

Two shifts are provided but only one dimension is given.

Used for shifting all values along a dimension.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/2017meb1219/01-tensor-operations


'https://jovian.ai/2017meb1219/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next
Important pyTorch functions are discussed in this notebook.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
